### ISSUE TITLE
Changes to spell settings are not picked up

### ISSUE THREAD

**Issue by Arvedui** [fgrsnau/ncm2-aspell#3]
I usually enable spell checking as needed or even change the settings when working on multilingual documents.
But aspell does not pick up these changes.

calling `ncm2#disable_for_buffer()` followed by `ncm2#enable_for_buffer()` works as a workaround but is annoying.

**Comment by fgrsnau** [comment]
The plugin should now pickup changes to 'spell' and the 'spelllang' option for the current buffer. Can you verify that it works as expected?

**Comment by Arvedui** [comment]
Works as expected now. Thanks!
